alter table TB_COMP drop foreign key FKD185AA40CA513C4D;
alter table TB_COMP drop foreign key FKD185AA40AA2A886C;
alter table TB_PRNT drop foreign key FKD18B9E799B2E0657;
alter table TB_PROJ drop foreign key FKD18B9E8EAA2A886C;
alter table TB_PROJ drop foreign key FKD18B9E8E4761F000;
alter table TB_USER drop foreign key FKD18DE6FC4761F000;
alter table tb_dir drop foreign key FKCB83DB3C6937BDC9;
alter table tb_file drop foreign key FKA4F874ADAA2A886C;
alter table tb_file_hist drop foreign key FKD4D207749B2855E6;
alter table tb_file_hist drop foreign key FKD4D20774AA2A886C;
alter table tb_proj_disc drop foreign key FKEDA20CA6BB5D5E33;
alter table tb_proj_disc drop foreign key FKEDA20CA6FC50F2EA;
alter table tb_proj_user drop foreign key FKEDA9EADCFC50F2EA;
alter table tb_proj_user drop foreign key FKEDA9EADC9B364284;
alter table tb_prov_prnt drop foreign key FK221C9CDFBFE6FD6;
alter table tb_prov_prnt drop foreign key FK221C9CD6BE475C8;
alter table tb_prov_proj drop foreign key FK221C9E2FC50F2EA;
alter table tb_prov_proj drop foreign key FK221C9E26BE475C8;
alter table tb_prov_user drop foreign key FK22412506BE475C8;
alter table tb_prov_user drop foreign key FK22412509B364284;
alter table tb_user_grup_user drop foreign key FK783BFE219B364284;
alter table tb_user_grup_user drop foreign key FK783BFE21812BFC00;
alter table tb_user_role drop foreign key FK37884BD99B364284;
drop table if exists TB_ADDR;
drop table if exists TB_COMP;
drop table if exists TB_DISC;
drop table if exists TB_PRNT;
drop table if exists TB_PROJ;
drop table if exists TB_USER;
drop table if exists TB_USER_GRUP;
drop table if exists tb_cnfg_parm;
drop table if exists tb_dir;
drop table if exists tb_file;
drop table if exists tb_file_hist;
drop table if exists tb_proj_disc;
drop table if exists tb_proj_user;
drop table if exists tb_prov;
drop table if exists tb_prov_prnt;
drop table if exists tb_prov_proj;
drop table if exists tb_prov_user;
drop table if exists tb_user_grup_user;
drop table if exists tb_user_role;
create table TB_ADDR (sq_addr bigint not null auto_increment, no_cep varchar(8), no_city varchar(255), no_cntr varchar(255), no_extr varchar(400), no_numb varchar(10), no_stat varchar(2), no_stre varchar(255), primary key (sq_addr));
create table TB_COMP (sq_comp bigint not null auto_increment, no_cnpj varchar(14), no_name varchar(400), nu_vers integer, sq_addf bigint, sq_dir bigint, primary key (sq_comp));
create table TB_DISC (sq_disc integer not null auto_increment, no_name varchar(255) not null, nu_vers integer not null, primary key (sq_disc));
create table TB_PRNT (sq_prnt bigint not null auto_increment, no_prnt varchar(255) not null, sq_cord bigint, primary key (sq_prnt));
create table TB_PROJ (sq_proj bigint not null auto_increment, no_name varchar(255) not null unique, sq_comp bigint not null, sq_dir bigint not null, primary key (sq_proj));
create table TB_USER (sq_user bigint not null auto_increment, no_mail varchar(255), no_logn varchar(255), no_name varchar(255), no_pass varchar(255), no_phon varchar(255), nu_vers varchar(255), sq_comp bigint not null, primary key (sq_user));
create table TB_USER_GRUP (sq_user_grup bigint not null auto_increment, no_user_grup varchar(255) not null, nu_vers integer, primary key (sq_user_grup));
create table tb_cnfg_parm (cd_cnfg_parm integer not null, no_valu varchar(255), primary key (cd_cnfg_parm));
create table tb_dir (sq_dir bigint not null auto_increment, no_dir varchar(255) not null, nu_vers integer not null, sq_prnt bigint, primary key (sq_dir));
create table tb_file (sq_file bigint not null auto_increment, tx_desc varchar(1000), no_name varchar(255) not null, no_orig_name varchar(255) not null, nu_size bigint not null, cd_situ integer not null, nu_vers integer not null, sq_dir bigint not null, primary key (sq_file));
create table tb_file_hist (sq_file_hist bigint not null auto_increment, nu_file_vers integer not null, nu_ip varchar(50) not null, no_name varchar(255) not null, cd_oper integer not null, no_orig_name varchar(255) not null, nu_size bigint not null, cd_situ integer not null, dt_tmst datetime not null, no_user varchar(255) not null, sq_dir bigint not null, sq_file bigint not null, primary key (sq_file_hist));
create table tb_proj_disc (sq_proj bigint not null, sq_disc integer not null, primary key (sq_proj, sq_disc), unique (sq_disc));
create table tb_proj_user (sq_proj bigint not null, sq_user bigint not null, primary key (sq_proj, sq_user), unique (sq_user));
create table tb_prov (sq_prov integer not null auto_increment, no_name varchar(255) not null, no_short_name varchar(30) not null, primary key (sq_prov));
create table tb_prov_prnt (sq_prov integer not null, sq_prnt bigint not null, primary key (sq_prov, sq_prnt));
create table tb_prov_proj (sq_prov integer not null, sq_proj bigint not null, primary key (sq_prov, sq_proj));
create table tb_prov_user (sq_prov integer not null, sq_user bigint not null, primary key (sq_prov, sq_user));
create table tb_user_grup_user (sq_user bigint not null, sq_user_grup bigint not null, primary key (sq_user, sq_user_grup));
create table tb_user_role (sq_user bigint not null, sq_role_id integer);
alter table TB_COMP add index FKD185AA40CA513C4D (sq_addf), add constraint FKD185AA40CA513C4D foreign key (sq_addf) references TB_ADDR (sq_addr);
alter table TB_COMP add index FKD185AA40AA2A886C (sq_dir), add constraint FKD185AA40AA2A886C foreign key (sq_dir) references tb_dir (sq_dir);
alter table TB_PRNT add index FKD18B9E799B2E0657 (sq_cord), add constraint FKD18B9E799B2E0657 foreign key (sq_cord) references TB_USER (sq_user);
alter table TB_PROJ add index FKD18B9E8EAA2A886C (sq_dir), add constraint FKD18B9E8EAA2A886C foreign key (sq_dir) references tb_dir (sq_dir);
alter table TB_PROJ add index FKD18B9E8E4761F000 (sq_comp), add constraint FKD18B9E8E4761F000 foreign key (sq_comp) references TB_COMP (sq_comp);
alter table TB_USER add index FKD18DE6FC4761F000 (sq_comp), add constraint FKD18DE6FC4761F000 foreign key (sq_comp) references TB_COMP (sq_comp);
alter table tb_dir add index FKCB83DB3C6937BDC9 (sq_prnt), add constraint FKCB83DB3C6937BDC9 foreign key (sq_prnt) references tb_dir (sq_dir);
alter table tb_file add index FKA4F874ADAA2A886C (sq_dir), add constraint FKA4F874ADAA2A886C foreign key (sq_dir) references tb_dir (sq_dir);
alter table tb_file_hist add index FKD4D207749B2855E6 (sq_file), add constraint FKD4D207749B2855E6 foreign key (sq_file) references tb_file (sq_file);
alter table tb_file_hist add index FKD4D20774AA2A886C (sq_dir), add constraint FKD4D20774AA2A886C foreign key (sq_dir) references tb_dir (sq_dir);
alter table tb_proj_disc add index FKEDA20CA6BB5D5E33 (sq_disc), add constraint FKEDA20CA6BB5D5E33 foreign key (sq_disc) references TB_DISC (sq_disc);
alter table tb_proj_disc add index FKEDA20CA6FC50F2EA (sq_proj), add constraint FKEDA20CA6FC50F2EA foreign key (sq_proj) references TB_PROJ (sq_proj);
alter table tb_proj_user add index FKEDA9EADCFC50F2EA (sq_proj), add constraint FKEDA9EADCFC50F2EA foreign key (sq_proj) references TB_PROJ (sq_proj);
alter table tb_proj_user add index FKEDA9EADC9B364284 (sq_user), add constraint FKEDA9EADC9B364284 foreign key (sq_user) references TB_USER (sq_user);
alter table tb_prov_prnt add index FK221C9CDFBFE6FD6 (sq_prnt), add constraint FK221C9CDFBFE6FD6 foreign key (sq_prnt) references TB_PRNT (sq_prnt);
alter table tb_prov_prnt add index FK221C9CD6BE475C8 (sq_prov), add constraint FK221C9CD6BE475C8 foreign key (sq_prov) references tb_prov (sq_prov);
alter table tb_prov_proj add index FK221C9E2FC50F2EA (sq_proj), add constraint FK221C9E2FC50F2EA foreign key (sq_proj) references TB_PROJ (sq_proj);
alter table tb_prov_proj add index FK221C9E26BE475C8 (sq_prov), add constraint FK221C9E26BE475C8 foreign key (sq_prov) references tb_prov (sq_prov);
alter table tb_prov_user add index FK22412506BE475C8 (sq_prov), add constraint FK22412506BE475C8 foreign key (sq_prov) references tb_prov (sq_prov);
alter table tb_prov_user add index FK22412509B364284 (sq_user), add constraint FK22412509B364284 foreign key (sq_user) references TB_USER (sq_user);
alter table tb_user_grup_user add index FK783BFE219B364284 (sq_user), add constraint FK783BFE219B364284 foreign key (sq_user) references TB_USER (sq_user);
alter table tb_user_grup_user add index FK783BFE21812BFC00 (sq_user_grup), add constraint FK783BFE21812BFC00 foreign key (sq_user_grup) references TB_USER_GRUP (sq_user_grup);
alter table tb_user_role add index FK37884BD99B364284 (sq_user), add constraint FK37884BD99B364284 foreign key (sq_user) references TB_USER (sq_user);
